name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup Elm environment
      uses: JorelAli/setup-elm@v1
      
    - name: Install elm-test
      run: npm install elm-test

    - name: Run tests
      run: elm-test
